Repository AY2324S2-CS2103T-T08-1/tp, pull requests merged in 2024-03, with the labels that each got.

#10 Add UI
  docs/AboutUs.md
  docs/images/JohnDoeUi.png
  docs/images/Ui.png
  docs/images/laney0808.png
  docs/team/laney0808.md
Labels: documentation

#7 Add alex-setyawan.png.jpg, update AboutUs.md
  docs/AboutUs.md
  docs/images/alex-setyawan.png
Labels: bug, documentation

#11 fix: update AboutUs.md
  docs/AboutUs.md
  docs/images/jovantanyk.png
  docs/team/jovantanyk.md
Labels: documentation

#12 docs: update user documentation
  README.md
  docs/_config.yml
Labels: documentation

#28 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#29 Update Menu Bar colour and content
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/images/question.png
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#32 Add user stories and use cases
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#30 feat: update ResultDisplay to ResultPanel
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultPanel.fxml
Labels: type.Enhancement, front-end

#34 Update Command Box UI
  src/main/resources/images/search_icon.png
  src/main/resources/images/search_icon_big.png
  src/main/resources/images/search_icon_black.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, front-end, priority.Medium

#37 Updated window title
  src/main/resources/images/stethoscope.png
  src/main/resources/view/MainWindow.fxml
Labels: front-end, type.Task, priority.Low

#38 fix: update size of Person and Result Panel
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultPanel.fxml
Labels: front-end, priority.Low

#33 Add fields
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Allergies.java
  src/main/java/seedu/address/model/person/BloodType.java
  src/main/java/seedu/address/model/person/Condition.java
  src/main/java/seedu/address/model/person/Country.java
  src/main/java/seedu/address/model/person/DateOfAdmission.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Diagnosis.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Sex.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/person/Symptom.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AllergiesTest.java
  src/test/java/seedu/address/model/person/BloodTypeTest.java
  src/test/java/seedu/address/model/person/ConditionTest.java
  src/test/java/seedu/address/model/person/CountryTest.java
  src/test/java/seedu/address/model/person/DateOfAdmissionTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/DiagnosisTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/SexTest.java
  src/test/java/seedu/address/model/person/StatusTest.java
  src/test/java/seedu/address/model/person/SymptomTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: back-end, type.Story, priority.High

#41 Fix commandbox colour
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: front-end

#40 Fix person card size to fit new main window size
  src/main/resources/view/PersonListCard.fxml
Labels: front-end, priority.Low

#45 Add optional field setters, key words and and parsers
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/BloodType.java
  src/main/java/seedu/address/model/person/Person.java
Labels: back-end

#51 Update nric, sex and status circle
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: front-end

#54 fix: Remove optional fields from Test
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug

#55 Update fields
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/person/BloodType.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: back-end, type.Story, priority.High

#57 Update create command and delete command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ImmuniMateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ImmuniMate.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyImmuniMate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImmuniMateParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: back-end, type.Story, priority.High

#85 Fix storage
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/OptionalSerializer.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImmuniMateParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: back-end, priority.High

#78 docs: update ModelClass diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation, priority.Low

#83 Add uml for create command
  docs/DeveloperGuide.md
  docs/diagrams/CreateCommand.puml
  docs/images/CreateCommand.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation

#104 feat: enable assertions
  build.gradle
Labels: priority.High
